using Portal.Application.Financeiro.UseCases.ObterLancamentosFinanceiros;

namespace Portal.Application.Financeiro.UseCases.ObterLancamentosFinanceirosPorPeriodo;

public class ObterLancamentosFinanceirosPorPeriodoResponse : ObterLancamentosFinanceirosResponse
{
}
